version: 2
builds:
  - id: score-flyio
    binary: score-flyio
    main: ./
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    targets:
      - linux_amd64_v1
      - linux_arm64
      - windows_amd64_v1
      - darwin_amd64_v1
      - darwin_arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^test'
