name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: fetch tags
        run: git fetch --force --tags
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: test
        run: go run gotest.tools/gotestsum@latest --format github-actions
      - name: lint
        run: >-
          go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          run --timeout 5m
      - name: tidy
        run: go mod tidy
      - name: diff
        run: git diff --exit-code
      - name: tag
        if: >-
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        run: bash .github/scripts/next-tag.sh
