name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup-go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: test
        run: go run gotest.tools/gotestsum@latest --format github-actions
      - name: lint
        run: >-
          go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          run --timeout 5m
      - name: tidy
        run: go mod tidy
      - name: diff
        run: git diff --exit-code
